name: Publish to rubygems

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Setup Rubygems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          bash .github/setup-rubygems.sh
      - name: Publish to Rubygems
        run: |
          gem build verify_vsp_client.gemspec
          gem push "verify_vsp_client-$(git describe --tags).gem"
